server:
  port: 8888

spring:
  application:
    name: zuul-application

# Zuul 配置项，对应 ZuulProperties 配置类
zuul:
  servlet-path: / # ZuulServlet 匹配的路径，默认为 /zuul
  # 路由配置项，对应 ZuulRoute Map
  routes:
    route_yudaoyuanma:
      path: /blog/**
      url: http://www.iocoder.cn
    route_oschina:
      path: /oschina/**
      url: https://www.oschina.net

management:
  endpoints:
    web:
      exposure:
        include: '*' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。
  endpoint:
    # Health 端点配置项，对应 HealthProperties 配置类
    health:
      enabled: true # 是否开启。默认为 true 开启。
      show-details: ALWAYS # 何时显示完整的健康信息。默认为 NEVER 都不展示。可选 WHEN_AUTHORIZED 当经过授权的用户；可选 ALWAYS 总是展示。
  server:
    port: 18888 # 单独设置端口，因为 8888 端口全部给 Zuul 了
