server:
  port: 18761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-node01
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-node02:28761/eureka/
