server:
  port: 8080
info:
  app:
    name: spring-boot-actuator
    version: 1.0.0
spring:
  security:
    user:
      name: admin
      password: admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: http://www.geekdigging.com
        allowed-methods: GET,POST
  #      base-path: /monitor
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true