server:
  port: 8080
spring:
  application:
    name: spring-boot-mail
  mail:
    host: smtp.qq.com
    username: 136736247
    password: xxxxxx
    default-encoding: UTF-8
    fromAddr: 136736247@qq.com
    nickName: inwsy