#Server settings
server:
  port: 8001
  servlet:
    context-path: /springboot
#spring profiles
spring:
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.198:3306/test_mysql?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: dba
    password: 123.com
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true    
#thymeleaf
  thymeleaf:
    #开启MVC Thymeleaf视图解析（默认值：true）
    enabled: true
    mode:  HTML5
    #模板编码
    encoding: UTF-8
    servlet:
    #Content-Type的值（默认值：text/html）
      content-type: text/html
    #开启模板缓存（默认值：true）
    cache: false
    

# MyBatis  
mybatis:
  configuration:
    #开启缓存，默认开启
    cache-enabled: true
    #开启懒加载
    lazy-loading-enabled: true
    #按需加载
    aggressive-lazy-loading: false
    #开启数据库字段转换驼峰命名法
    map-underscore-to-camel-case: true
    #设置MyBatis mapper的别名所在的包
    #type-aliases-package: com.abc.demo.domain    
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.abc.demo.domain
 
 
      


    


  
