server:
   port: 8100
   servlet:
      context-path: /
      session:
         timeout: 1800 # Session超时时间，-1代表永不过期（默认30分钟）
   tomcat:
      uri-encoding: UTF-8
      max-threads: 800
      min-spare-threads: 30
logging:
   level:
      com.jun.plugin: DEBUG
      tk.mybatis: DEBUG
      org.springframework: WARN
spring:
   profiles:
      active: dev
   thymeleaf:
      cache: false
      mode: LEGACYHTML5
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   servlet:
      multipart:
         max-file-size: 100MB
         max-request-size: 100MB
   mail:
      host: smtp.qq.com #发送邮件服务器
      username: 245783660@qq.com #发送邮件的邮箱地址
      password: 123 #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
      properties.mail.smtp.port: 465 #端口号465或587
      from: 245783660@qq.com # 发送邮件的地址，和上面username一致
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      properties.mail.smtp.ssl.enable: true
      default-encoding: utf-8
# Shiro
shiro:
   user:
      loginUrl: /login
      unauthorizedUrl: /error/403
      indexUrl: /index
   session:
      globalSessionTimeout: 600 #单机环境，session过期时间为60分钟 60 * 60
   cookie:
      domain: 
      path: /
      httpOnly: true
      maxAge: 30
      cipherKey: DiFWf0w+lIg3gLhL8iWm/g== # 设置密钥，务必保持唯一性（生成方式，直接拷贝到main运行即可）KeyGenerator keygen = KeyGenerator.getInstance("AES"); SecretKey deskey = keygen.generateKey(); System.out.println(Base64.encodeToString(deskey.getEncoded()));
mybatis:
   type-aliases-package: com.jun.plugin.modules.*.model
   mapper-locations: classpath*:/mapper/**/*.xml
   configuration:
      map-underscore-to-camel-case: true
mapper:
   mappers: com.jun.plugin.common.mapper.MyMapper
   not-empty: false
   identity: MYSQL
pagehelper:
   helperDialect: mysql
   reasonable: true
   supportMethodsArguments: true
   params: count=countSql
# 系统自定义全局配置，可根据实际需要扩展使用
global:
   workDir: D:/web-project/ht-file # 文件路径 示例（ Windows配置D:/web-project/profile，Linux配置 /home/hplus-file/profile）
   redisrun: false # 开启redis值：true, 不开启redis值：false