spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: @spring.datasource.url@
    username: @spring.datasource.username@
    password: @spring.datasource.password@
    platform: mysql
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
  aop:
    #Add @EnableAspectJAutoProxy
    auto: true
    #当我们需要使用CGLIB来实现AOP的时候，需要配置 spring.aop.proxy-target-class=true ，不然默认使用的是标准Java的实现。
    proxy-target-class: true
  redis:
    database: 0
    host: @redis.host@
    port: 6379
    password: @redis.password@
    timeout: 30000
    pool:
      max-active: 8
      max-wait: 60000
      max-idle: 8
      min-idle: 0
  # 返回标准时间格式而不是毫秒值
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置时区。防止出现时间差八小时
    time-zone: GMT+8

  # 热部署
  devtools:
    restart:
      enabled: true
  mail:
    host: @mail.host@
    username: @mail.username@
    password: @mail.password@
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mapper:
  not-empty: false
  identity: MYSQL

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.chentongwei.core.system.entity,com.chentongwei.core.tucao.entity,com.chentongwei.core.user.entity,com.chentongwei.core.common.entity,com.chentongwei.common.entity

pagehelper:
  helper-dialect: mysql
  reasonable: false
  offset-as-page-num: true
  row-bounds-with-count: true
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:log4j2-spring.xml

server:
  port: 9999
  tomcat:
    ## tomcat最大线程数，默认为200
    max-threads: 300
    uri-encoding: UTF-8