server:
  port: 80
  servlet:
    context-path: /

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT%2B8
        username: root
        password: 123456
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 6000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j 
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #配置静态资源
    resources:
        static-locations: classpath:/static/

mybatis:
  config-location: classPath:mybatis/mybatis-config.xml
  mapper-locations: xml/**/*.xml
  type-aliases-package: com.mall.common.model
  
  


