server:
  port: 8888

spring:
  application:
    name: zuul-application

  cloud:
    nacos:
      # Nacos 作为注册中心的配置项
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址

# Zuul 配置项，对应 ZuulProperties 配置类
zuul:
  servlet-path: / # ZuulServlet 匹配的路径，默认为 /zuul
  # 路由配置项，对应 ZuulRoute Map
  routes:
    route_yudaoyuanma:
      path: /blog/**
      url: http://www.iocoder.cn
    route_oschina:
      path: /oschina/**
      url: https://www.oschina.net
    route_users:
      path: /users/**
      service-id: user-service
