server:
  # 端口配置
  port: 9090


spring:
  # 启动环境配置
  profiles:
    active: druid

# MyBatis 配置
mybatis-plus:
  # XML 扫描类路径
  mapper-locations: classpath*:com/pearframe/modules/**/xml/*Mapper.xml
  # 别名 领域模型 扫描包路径
  type-aliases-package: com.pearframe

  # 日志 配置文件
  logging:
    config:classpath: static/logback.xml