## tomcat 配置
server:
  ## 监听端口
  port: 9292

## spring 配置
spring:
  profiles:
    ## 激活配置
    active: dev

## mybatis plus 配置
mybatis-plus:
  ## mapper 文件位置
  mapper-locations: classpath*:com/pearadmin/modules/**/xml/*Mapper.xml
  ## domain 实体别名
  type-aliases-package: com.pearadmin