management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream' # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 * ，可以开放所有端点。

spring:
  application:
    name: hystrix-demo # 应用名

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/ # Eureka-Server 地址
