server:
  port: 8081

spring:
  application:
    name: feign-service # 服务名

  # Zipkin 配置项，对应 ZipkinProperties 类
  zipkin:
    base-url: http://127.0.0.1:9411 # Zipkin 服务的地址

  # Spring Cloud Sleuth 配置项
  sleuth:
    # Spring Cloud Sleuth 针对 Web 组件的配置项，例如说 SpringMVC
    web:
      enabled: true # 是否开启，默认为 true
    # Spring Cloud Sleuth 针对 Feign 组件的配置项，对应 SleuthFeignProperties 类
    feign:
      enabled: true # 是否开启，默认为 true
