spring:
  # R2DBC 配置，对应 R2dbcProperties 配置类
  r2dbc:
    url: mysql://47.112.193.81:3306/lab-27-webflux-r2dbc
    username: lab-27-webflux-r2dbc
    password: 0ed86@11-r2Dbc123
#  jasync:
#    r2dbc:
#      host: 47.112.193.81
#      port: 3306
#      database: lab-27-webflux-r2dbc
#      username: lab-27-webflux-r2dbc
#      password: 0ed86@11-r2Dbc123
