# Redis数据库索引（默认为0）
# Redis服务器地址
spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 100