spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://192.168.0.105/sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
    redis:
      host: 192.168.0.105
      port: 6379
server:
  context-path: /sell

wechat:
  mpAppId: wx75eab88f02a2e739
  mpAppSecret: xxxxxxxxx
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  openAppId: wx6ad144e54af6xxxx
  openAppSecret: 91a2ff6d38a2bbccfb7e9f907910xxxx
  mchAppId: wxd898fcb01713c658
  notifyUrl: http://mpsell.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: gyDwQ9Ies-XwaqtbdspXJP8QCdHVyAbEggSIt0kNN94

projectUrl:
  wechatMpAuthorize: http://mpsell.natapp1.cc
  wechatOpenAuthorize: http://mpsell.natapp1.cc
  sell: http://mpsell.natapp1.cc
  openid: oTgZpwWYCeCLQaPtso5aGoLD_zQY
logging:
  level:
     top.linxz.sell.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml