spring:
  application:
    name: demo-consumer # Spring 应用名
server:
  port: 28080 # 服务器端口。默认为 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:woshimima@127.0.0.1:8761/eureka/ # Eureka-Server 地址
